# Generated by Django 4.2.25 on 2025-11-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='artist_profiles/')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artist_products/')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('year_created', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, help_text='Depth in inches', max_digits=6, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tags_keywords', models.CharField(blank=True, help_text='Comma-separated tags/keywords', max_length=200, null=True)),
                ('framed', models.BooleanField(default=False)),
                ('signed', models.BooleanField(default=False)),
                ('certificate_of_authenticity', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
    ]
